name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/10 * * * *"
  
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: JNzH/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b725327ebd379b9c5bf18bda1e60ed84
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
